name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Remove the next step until you actually have tests
      # - name: Run tests
      #   run: pytest

      # ===== optional: auto-deploy to Render once you add your service webhook =====
      # - name: Trigger Render deploy
      #   run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
