name: nightly-crawl

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  crawl-and-embed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl and embed
        run: |
          python crawler.py crawl
          python crawler.py embed
